name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - "preprod"
  workflow_dispatch:

jobs:
  production-deploy:
    if: ${{ github.ref_name == 'prod' && github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.PROD_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.PROD_RENDER_API_KEY }}

  preproduction-deploy:
    if: ${{ github.ref_name == 'preprod' && github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.PREPROD_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.PREPROD_RENDER_API_KEY }}
          wait-for-success: true
