name: CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"
          cache: maven
      - run: echo "TOKEN_SIGNING_KEY=$ {{ secrets.TOKEN_SIGNING_KEY }}" >> $GITHUB_ENV
      - run: echo "The key is $TOKEN_SIGNING_KEY HERE"
      - run: chmod +x mvnw
      - run: ./mvnw test

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "corretto"
          cache: maven
      - run: chmod +x format.sh
      - run: ./format.sh
